### ISSUE TITLE
Request: Connect to Live API

### ISSUE THREAD

**Issue by mitchross** [tyroprogrammer/learn-react-app#35]
Can you please add an example where we connect to an actual working API? Would be great to see how to manage APIs keys, constants, etc.

**Comment by tyroprogrammer** [comment]
Working with actual working API is not different in React than in other frameworks/libraries. Please refer to this - https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch for more information on how to use fetch API. Since this is not specific to React, this is outside the scope of this tutorial.
